server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: activity-service
  datasource:
    url: jdbc:mysql://127.0.0.1:33306/activity
    username: root
    password: 123456
  activiti:
    check-process-definitions: false